openapi: 3.0.0
info:
  title: Class Series API
  version: 1.0.0
paths:
  /api/class-series/{seriesId}:
    get:
      summary: Get a class series
      parameters:
        - name: seriesId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A class series
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClassSeries"
    patch:
      summary: Update a class series
      parameters:
        - name: seriesId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClassSeriesUpdate"
      responses:
        "200":
          description: The updated class series
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClassSeries"
  /api/class-series/{seriesId}/extend:
    post:
      summary: Extend a class series
      parameters:
        - name: seriesId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                months:
                  type: integer
      responses:
        "200":
          description: The number of sessions created
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
components:
  schemas:
    ClassSeries:
      type: object
      properties:
        seriesId:
          type: string
        branchId:
          type: string
        teacherId:
          type: string
        studentId:
          type: string
        subjectId:
          type: string
        classTypeId:
          type: string
        boothId:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        startTime:
          type: string
          format: time
        endTime:
          type: string
          format: time
        duration:
          type: integer
        daysOfWeek:
          type: array
          items:
            type: integer
        status:
          type: string
        generationMode:
          type: string
        lastGeneratedThrough:
          type: string
          format: date
        conflictPolicy:
          type: object
        notes:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    ClassSeriesUpdate:
      type: object
      properties:
        branchId:
          type: string
        teacherId:
          type: string
        studentId:
          type: string
        subjectId:
          type: string
        classTypeId:
          type: string
        boothId:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        startTime:
          type: string
          format: time
        endTime:
          type: string
          format: time
        duration:
          type: integer
        daysOfWeek:
          type: array
          items:
            type: integer
        status:
          type: string
        generationMode:
          type: string
        lastGeneratedThrough:
          type: string
          format: date
        conflictPolicy:
          type: object
        notes:
          type: string
