openapi: 3.0.0
info:
  title: Class Series API
  version: 1.0.0
paths:
  /api/class-series:
    get:
      summary: List class series
      parameters:
        - name: studentId
          in: query
          schema:
            type: string
        - name: teacherId
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
        - name: branchId
          in: query
          schema:
            type: string
      responses:
        "200":
          description: A list of class series
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ClassSeries"
components:
  schemas:
    ClassSeries:
      type: object
      properties:
        seriesId:
          type: string
        branchId:
          type: string
        teacherId:
          type: string
        studentId:
          type: string
        subjectId:
          type: string
        classTypeId:
          type: string
        boothId:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        startTime:
          type: string
          format: time
        endTime:
          type: string
          format: time
        duration:
          type: integer
        daysOfWeek:
          type: array
          items:
            type: integer
        status:
          type: string
        generationMode:
          type: string
        lastGeneratedThrough:
          type: string
          format: date
        conflictPolicy:
          type: object
        notes:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
