openapi: 3.0.0
info:
  title: Class Series API
  version: 1.0.0
paths:
  /api/class-series/summary:
    get:
      summary: Get a summary of class series for a student
      parameters:
        - name: studentId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A summary of class series for a student
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClassSeriesSummary"
components:
  schemas:
    ClassSeriesSummary:
      type: object
      properties:
        totalRegular:
          type: integer
        bySubject:
          type: array
          items:
            type: object
            properties:
              subjectId:
                type: string
              count:
                type: integer
