openapi: 3.0.3
info:
  title: Cancel Class Sessions
  version: 1.0.0
paths:
  /api/class-sessions/cancel:
    post:
      summary: Cancel class sessions (single, batch, or from a series start date)
      description: |
        Cancels specific sessions by `classIds`, or all sessions for a series from a given date `fromDate`.
        When used with `seriesId` and `fromDate`, cancels the selected occurrence date and all future occurrences.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                classIds:
                  type: array
                  items:
                    type: string
                  description: Specific session IDs to cancel (single or batch)
                seriesId:
                  type: string
                  description: Series identifier; used with `fromDate`
                fromDate:
                  type: string
                  pattern: '^\d{4}-\d{2}-\d{2}$'
                  description: ISO date (YYYY-MM-DD); boundary inclusive (>= fromDate)
                reason:
                  type: string
                  description: Optional reason; UI may store separately
              oneOf:
                - required: [classIds]
                - required: [seriesId, fromDate]
      responses:
        "200":
          description: Cancel request applied
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: {}
                  message:
                    type: string
                  updatedCount:
                    type: integer
                  pagination:
                    type: object
                    properties:
                      total: { type: integer }
                      page: { type: integer }
                      limit: { type: integer }
                      pages: { type: integer }
        "400":
          description: Invalid input
        "500":
          description: Server error
